### ISSUE TITLE
supplied diagram likely outdated

### ISSUE THREAD

**Issue by hpl002** [bpmn-io/react-bpmn#10]
Great little project you have put together here. Found it to be a very good starting point, so i appreciate the work you have done.
 
Noticed a slight hicky in your example that caused me some headaches in the start. 

Was getting this error:

`js
failed to show diagram Error: failed to parse document as <bpmn:Definitions>
    at ai (bpmn-navigated-viewer.production.min.js:2)
    at bpmn-navigated-viewer.production.min.js:2
    at new Promise (<anonymous>)
    at gi.fromXML (bpmn-navigated-viewer.production.min.js:2)
    at Li.fromXML (bpmn-navigated-viewer.production.min.js:2)
    at bpmn-navigated-viewer.production.min.js:23
    at new Promise (<anonymous>)
    at Sr.<anonymous> (bpmn-navigated-viewer.production.min.js:23)
    at Sr.importXML (bpmn-navigated-viewer.production.min.js:2)
    at ReactBpmn.displayDiagram (index.esm.js:163)
...
`
 
Seems as if the [referenced bpmn diagram in your example](https://github.com/bpmn-io/react-bpmn/blob/master/example/public/diagram.bpmn) might be outdated as it breaks during parsing. From an earlier issue i found a sandbox where you referenced [some other file](https://cdn.statically.io/gh/camunda/camunda-modeler/v3.5.0/resources/diagram/simple.bpmn)

Seems like the diagram simply needs to be updated or swapped out for something else

**Comment by pinussilvestrus** [comment]
Thanks for reporting!

Can you maybe update your details by using [our template](https://github.com/bpmn-io/react-bpmn/issues/new?assignees=&labels=bug&template=BUG_REPORT.md)? It would be especially interesting how we can reproduce the error you got. Otherwise, updating the diagram might do the trick, but we'd like to understand the problem first.

**Comment by hpl002** [comment]
I can formalize this later, but for now i would suggest simply following your own usage instructions.

While i suspect the supplied diagram is valid BPMN it is not valid input for the bpmn-js parser.

Parser expects to find <bpmn:Definitions> and the diagram does not have this element.

**Comment by pinussilvestrus** [comment]
That's the thing. The diagram works perfectly fine for me locally, given the setup provided in the README. That's why I am asking for your setup.

**Comment by nikku** [comment]
> Seems like the diagram simply needs to be updated or swapped out for something else

The difference between the referenced file and _some other file_ is that some other file is loaded remotely. 

I guess whatever bundling setup you use attempts to inline the diagram, but cannot do it, as inlining (and converting it to JavaScript) fails.

Closing this issue.

**Comment by nikku** [comment]
To verify the diagram works, load it into [demo.bpmn.io](https://demo.bpmn.io/).
