### ISSUE TITLE
Uncaught ReferenceError: ReactBpmn is not defined

### ISSUE THREAD

**Issue by masoud-moghini** [bpmn-io/react-bpmn#13]
__Describe the Bug__

__Steps to Reproduce__

1. clone code
2. npm install
3. npm start
4. Go to http://localhost:5000/public/index.html

__Actual Behavior__

![image](https://user-images.githubusercontent.com/17137345/110426138-68e23800-805a-11eb-8243-d48fced2ca15.png)

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 14.16.0 LTS]
- OS: [e.g. Windows 10]

**Comment by nikku** [comment]
Getting it running was a little bit harder than it should be.

I've added https://github.com/bpmn-io/react-bpmn/commit/51eef83caa22e34891f08ba3c66a05d85d73017d to use the release package in the example. Should work for you now.
