### ISSUE TITLE
Running the example doesn't work for me

### ISSUE THREAD

**Issue by kevinm416** [bpmn-io/react-bpmn#14]
__Describe the Bug__
When I run the example using the instructions, I see an empty web page instead of the viewer.

__Steps to Reproduce__

```
[~/react-bpmn/example]$ npm install

up to date, audited 36 packages in 354ms

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

[~/react-bpmn/example]$ npm start

> react-bpmn-example@0.0.0 start
> sirv . start --dev

  Your application is ready~! 🚀

  - Local:      http://localhost:5000
  - Network:    Add `--host` to expose

────────────────── LOGS ──────────────────

  [09:15:39] 404 ─ 1.25ms ─ /
  [09:15:39] 404 ─ 0.14ms ─ /favicon.ico
```

__Expected Behavior__

I expect to see the bpm viewer.

__Environment__

- Host Firefox 104.0.1 (64-bit), npm v8.11.0
- OS: NixOS 22.05.2889.67e45078141
- Library version: 0.0.0

![Screenshot from 2022-09-11 09-17-59](https://user-images.githubusercontent.com/526698/189538083-06e4c821-dbe1-4621-a43b-bc3190acf816.png)

**Comment by pinussilvestrus** [comment]
I can reproduce that, thanks for opening!

The example could need an update. We are open to contributions that improve the situation 👍

**Comment by kevinm416** [comment]
Unfortunately I'm opening this issue because I would like to use this
library, but can't figure out how to because the example doesn't work. I
don't have the experience to fix the example.

**Comment by pinussilvestrus** [comment]
I will try out whether this is a quick fix. Integration examples should work as expected.

**Comment by pinussilvestrus** [comment]
I just investigated it and saw the [example's README](https://github.com/bpmn-io/react-bpmn/blob/master/example/README.md#run-the-example) gives an important hint: The example is accessible via http://localhost:5000/public/index.html after startup. Can you verify that this works for you?

**Comment by kevinm416** [comment]
Thanks for helping me out! I'm clearly new to this :) Yes, I just wasn't opening the right page.
