### ISSUE TITLE
React functional component example

### ISSUE THREAD

**Issue by joey-kwl** [bpmn-io/react-bpmn#23]
### What should we do?

Make a new example that uses React Functional component. Optional with Typescript.

### Why should we do it?

React is moving away from Class based component. I already have a working example.  https://github.com/joey-kwl/React-Typescript-BPMN-example

**Comment by nikku** [comment]
Sound great. Would you like to contribute your example? Should be basically about updating [this](https://github.com/bpmn-io/react-bpmn/blob/main/example/public/index.html#L70) to a function component, right?

**Comment by joey-kwl** [comment]
Sure

**Comment by joey-kwl** [comment]
Not sure how much time you have, but you can also rewrite the [source ](https://github.com/bpmn-io/react-bpmn/blob/main/src/index.jsx)to Functional component too.

Something like this: https://github.com/joey-kwl/React-Typescript-BPMN-example/blob/main/src/Bpmn.tsx
