### ISSUE TITLE
when  show  bpmn file have error

### ISSUE THREAD

**Issue by ceu** [bpmn-io/react-bpmn#4]
![屏幕快照 2019-08-27 17 06 39](https://user-images.githubusercontent.com/13114273/63757804-4875e100-c8ed-11e9-8bfd-a6de18f69645.png)

**Comment by ceu** [comment]
@nikku

**Comment by pinussilvestrus** [comment]
Hi @ceu,

without any additional information regarding your project setup, we will not be able to help you.

- What did you do?
- What diagram did you try to import?
- What does your setup look like?

Bringing your issue in [our template form](https://github.com/bpmn-io/bpmn-js/issues/new?template=BUG_REPORT.md) would also help us.

**Comment by nikku** [comment]
This is probably related to the fact that you do not provide a valid BPMN 2.0 file to open.
