### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by greybax** [bpmn-io/react-bpmn#6]
I did follow steps:

* `npm install --save react-bpmn`
* done exactly the same steps which described in "Usage" section of `readme.md`
* but i couldn't to see the graph editor and getting the error like on screenshot below:

![image](https://user-images.githubusercontent.com/3235047/69379451-5bd2e700-0c65-11ea-8419-2338e16ddbc0.png)

**Comment by pinussilvestrus** [comment]
Hi @greybax ,

can you give the full error your error handler received? Which would mean, if you follow the setup example

import ReactBpmn from 'react-bpmn';

```js
function App(props) {

  /* ... */

  function onError(err) {
    console.log(err.stack);
  }

  return (
    <ReactBpmn
      url="/public/diagram.bpmn"
      onError={ onError }
    />
  );
}
```

Second thing: I would assume the error then belongs to your imported diagram. Can you post the bpmn diagram you used?
