### ISSUE TITLE
Module not found:Can't resolve 'bpmn-js/dist/bpmn-navigated-viewer.production.min.js'

### ISSUE THREAD

**Issue by yashshukla1912** [bpmn-io/react-bpmn#7]
```
Failed to compile
./node_modules/react-bpmn/dist/index.esm.js

Module not found: Can't resolve 'bpmn-js/dist/bpmn-navigated-viewer.production.min.js' in '/home/React/location/node_modules/react-bpmn/dist'
```

__Describe the Bug__

Module not Found 'bpmn-js/dist/bpmn-navigated-viewer.production.min.js'

__Steps to Reproduce__

1.` npm install react-bpmn` in react app
2. Followed the steps mentioned in README.md
3. On running the app, i get this error

__Expected Behavior__

__Environment__

- Host (Browser/Node version), if applicable: Chrome 79/node:10.16
- OS: Ubuntu 18.04
- Library version: 0.1.1

**Comment by nikku** [comment]
Works in my sandbox: https://codesandbox.io/s/eloquent-river-42gfc.

Did you `npm install bpmn-js`, which is required as a peer dependency?

**Comment by yashshukla1912** [comment]
Thanks! that worked.
Now I am getting another error,  It doesn't display the diagram

`failed to show diagram Error: failed to parse document as <bpmn:Definitions>
    at Ei (bpmn-navigated-viewer.production.min.js:5132)
    at bpmn-navigated-viewer.production.min.js:5445`

I uploaded the file here [bpmn.io](https://demo.bpmn.io/) , it worked, but in the sandbox you provided i changed the bpmn file and it gives error.
sandbox: [https://codesandbox.io/s/crimson-glade-9cq34](https://codesandbox.io/s/crimson-glade-9cq34?fontsize=14&hidenavigation=1&theme=dark)

**Comment by nikku** [comment]
If you checkout your `reactPOC.bpmn` you'll recognize it is a HTML file, not a BPMN diagram.

**Comment by hpl002** [comment]
> Works in my sandbox: https://codesandbox.io/s/eloquent-river-42gfc.
> 
> Did you `npm install bpmn-js`, which is required as a peer dependency?

why not add this as a required dependency in the package.json so that this too is downloaded when downloading react-bpmn?

**Comment by GTall131** [comment]
Hi, vscode is telling me it could not find a declaration file when trying to import 'bpmn-js/dist/bpmn-navigated-viewer.production.min.js'. I have bpmn-js installed as a dependency. I'm not using TypeScript by the way in case that's relevant. Wondering if anyone has any advice?
