### ISSUE TITLE
how can i setNodeColor with  react ?

### ISSUE THREAD

**Issue by flrainbow** [bpmn-io/react-bpmn#8]

**Comment by flrainbow** [comment]
elementRegistry.get(id)  can't get the  element，
so modeling.setColor(elements,{}) can't come true

**Comment by nikku** [comment]
Please share additional context, i.e. [an example](https://codesandbox.io/s/bpmn-modeler-6wnf7) that clearly indicates where you're running into an error.

We cannot help you, otherwise.

**Comment by flrainbow** [comment]
![image](https://user-images.githubusercontent.com/23025529/83493223-08c8cf00-a4e7-11ea-8ce5-0d353f44492c.png)
![image](https://user-images.githubusercontent.com/23025529/83493470-6826df00-a4e7-11ea-919a-2467868c908e.png)

**Comment by philippfromme** [comment]
There is no element with that ID in your diagram. The reason is that you're not waiting for the import to finish. `importXML` takes a callback that will be executed once the import is finished.
